---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Add apt repository keys
      apt_key:
        url: "{{ item }}"
      loop:
        - https://packages.microsoft.com/keys/microsoft.asc
        - https://dl.google.com/linux/linux_signing_key.pub

    - name: Add apt repositories
      apt_repository:
        repo: "{{ item }}"
      loop:
        - deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        - deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main

    - name: Keep all softwares up to date
      apt:
        update_cache: yes
        upgrade: full

    - name: Remove unnecessary programs
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - ubuntu-web-launchers
        - thunderbird
        - firefox
        - gnome-calendar
        - gnome-todo
        - libreoffice*

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
        purge: yes

    # Desktop environment: GNOME
    - name: Install python-psutil (python2) # For dconf module
      apt:
        name: python-psutil

    - name: Map caps lock to ctrl
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['ctrl:nocaps']"
      become_user: "{{ ansible_env.SUDO_USER }}"

    - name: Turn on Auto-hide the dock
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
        value: "false"
      become_user: "{{ ansible_env.SUDO_USER }}"

    - name: Install Visual Studio Code
      apt:
        name: code

    # TODO: idempotent
    - name:
      shell: code --install-extension shan.code-settings-sync
      become_user: "{{ ansible_env.SUDO_USER }}"

    - name: Install Git
      apt:
        name: git

    - name: Configure Git
      git_config:
        scope: global
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - { name: user.email, value: seunghunee@gmail.com }
        - { name: user.name, value: Shin Seunghun }

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
