---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    # OS: Ubuntu
    ## Linux Kernel
    - name: set inotify watchers's maximum limit
      sysctl:
        name: fs.inotify.max_user_watches
        value: 524288
        reload: yes

    ## Package manager: apt
    - name: Keep all softwares up to date
      apt:
        update_cache: yes
        upgrade: full

    - name: Remove unnecessary programs
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - firefox

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
        purge: yes

    ## Desktop environment: GNOME
    - include: ppa-install.yml
      vars:
        name: Numix
        pkg_name: "{{ item }}"
        repo: ppa:numix/ppa
      loop:
        - numix-gtk-theme
        - numix-icon-theme-circle

    - name: Set a profile for dconf databases
      copy:
        src: configs/user
        dest: /etc/dconf/profile/user

    - name: Create the gnome dconf database directory
      file:
        path: /etc/dconf/db/gnome.d
        state: directory

    - name: Set a gnome dconf config file
      copy:
        src: configs/gnome.cfg
        dest: /etc/dconf/db/gnome.d/gnome.cfg
      register: gnome

    - name: Update dconf
      shell: dconf update
      when: gnome.changed

    - name: Remove personal special folders
      file:
        path: ~/{{ item }}
        state: absent
      become_user: "{{ ansible_env.SUDO_USER }}"
      loop:
        - Documents
        - Downloads
        - Music
        - Pictures
        - Public
        - Templates
        - Videos

    - name: Disable the automatic special folder creation
      copy:
        src: configs/user-dirs.conf
        dest: ~/.config/user-dirs.conf
      become_user: "{{ ansible_env.SUDO_USER }}"

    # Editor: Visual Studio Code
    - include: ppa-install.yml
      vars:
        name: Visual Studio Code
        pkg_name: code
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        key_url: https://packages.microsoft.com/keys/microsoft.asc

    - name: Install vscode sync extension
      shell: code --install-extension shan.code-settings-sync
      become_user: "{{ ansible_env.SUDO_USER }}"

    # Version Control system: Git
    - name: Install Git
      apt:
        name: git

    - name: Configure Git
      git_config:
        scope: global
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - { name: user.email, value: seunghunee@gmail.com }
        - { name: user.name, value: Shin Seunghun }

    # Web browser: Google Chrome
    - include: ppa-install.yml
      vars:
        name: Google Chrome
        pkg_name: google-chrome-stable
        repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
        key_url: https://dl.google.com/linux/linux_signing_key.pub

    # Node
    - name: nvm
      shell: >
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      become_user: "{{ ansible_env.SUDO_USER }}"
