---
- hosts: localhost
  connection: local
  tasks:
    # OS: Ubuntu
    ## Laptop lid
    - name: make Ubuntu not go in suspend when laptop lid is closed
      lineinfile:
        path: /etc/systemd/logind.conf
        line: HandleLidSwitch=ignore
      become: yes

    ## Linux Kernel
    - name: set inotify watchers's maximum limit
      sysctl:
        name: fs.inotify.max_user_watches
        value: "524288"
        reload: yes
      become: yes

    ## Package manager: apt
    - name: Keep all softwares up to date
      apt:
        update_cache: yes
        upgrade: full
      become: yes

    - name: Remove unnecessary programs
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - firefox
        - evince
        - gedit
      become: yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
      become: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
        purge: yes
      become: yes

    ## Desktop environment: GNOME
    - name: Install python3-psutil (python3) # For dconf module
      apt:
        name: python3-psutil
      become: yes

    - name: Enable dark theme
      dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"

    - name: Auto-hide the Dock
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
        value: "false"

    - name: Remove appliction icons from dock
      dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "['']"

    ### Key bindings
    - name: Map caps lock to ctrl
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['ctrl:nocaps']"

    - name: Unbind [Ctrl + Alt + Left]
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left"
        value: "['<Super>Page_Up']"

    - name: Unbind [Ctrl + Alt + Right]
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right"
        value: "['<Super>Page_Down']"

    - name: Unbind [Ctrl + Shift + Alt + up] from move-to-workspace-up
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-up"
        value: "['<Super><Shift>Page_Up']"

    - name: Unbind [Ctrl + Shift + Alt + down] from move-to-workspace-down
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-down"
        value: "['<Super><Shift>Page_Down']"

    - name: Unbind [Alt + Tab] from switch-applications
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-applications"
        value: "['<Super>Tab']"

    - name: Bind [Alt + Tab] to switch-windows
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-windows"
        value: "['<Alt>Tab']"

    - name: Unbind [Alt + Shift + Tab] from switch-applications-backward
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward"
        value: "['<Shift><Super>Tab']"

    - name: Bind [Alt + Shift + Tab] to switch-windows-backward
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
        value: "['<Shift><Alt>Tab']"

    - name: Unbind [Alt + F8]
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/begin-resize"
        value: "['']"

    ### Input framework: Ibus
    - name: Install ibus hangul (Korean)
      apt:
        name: ibus-hangul
      register: ibus_hangul
      become: yes

    - name: Install ibus mozc (Japanese)
      apt:
        name: ibus-mozc
      register: ibus_mozc
      become: yes

    - name: Restart ibus daemon
      shell: ibus restart
      when: ibus_hangul.changed or ibus_mozc.changed

    - name: Set input sources
      dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'us'), ('ibus', 'hangul'), ('ibus', 'mozc-jp')]"

    - name: Disable ibus's hotkey # Ctrl+Shift+E가 기본으로 할당되어 있다
      dconf:
        key: "/desktop/ibus/panel/emoji/hotkey"
        value: "@as []"

    - name: Disable ibus's unicode hotkey # Ctrl+Shift+U가 기본으로 할당되어 있다
      dconf:
        key: "/desktop/ibus/panel/emoji/unicode-hotkey"
        value: "@as []"

    - name: Set ibus-hangul's initial input mode to hangul
      dconf:
        key: "/org/freedesktop/ibus/engine/hangul/initial-input-mode"
        value: "'hangul'"

    # Terminal: Bash(GNOME Terminal)
    - name: Disable XON/XOFF for i-search forward
      lineinfile:
        path: ~/.bashrc
        line: stty -ixon
        create: yes

    # Editor: Visual Studio Code
    - import_tasks: ppa-install.yml
      vars:
        name: Visual Studio Code
        pkg_name: code
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        key_url: https://packages.microsoft.com/keys/microsoft.asc
      become: yes

    - name: Set Visual Studio Code as default editor
      lineinfile:
        path: ~/.bashrc
        line: export EDITOR="code -w"
        create: yes

    # Version Control system: Git
    - name: Install Git
      apt:
        name: git
      become: yes

    - name: Configure Git
      git_config:
        scope: global
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - { name: user.email, value: seunghunee@gmail.com }
        - { name: user.name, value: Shin Seunghun }
        - { name: diff.tool, value: vscode }
        - {
            name: difftool.vscode.cmd,
            value: code --wait --diff $LOCAL $REMOTE,
          }
        - { name: help.autocorrect, value: prompt }

    # Web browser: Google Chrome
    - import_tasks: ppa-install.yml
      vars:
        name: Google Chrome
        pkg_name: google-chrome-stable
        repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
        key_url: https://dl.google.com/linux/linux_signing_key.pub
      become: yes

    # Tools
    - name: Install curl
      apt:
        name: curl
      become: yes

    - name: Install kubectl
      snap:
        name: kubectl
        classic: true
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
      become: yes

    - name: Install mold
      apt:
        name: mold
      become: yes

    # Rust
    - name: Install rustup
      shell: >
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "{{ ansible_env.HOME }}/.rustup"

    - name: Add mold as the default linker for Rust
      blockinfile:
        path: ~/.cargo/config.toml
        create: true
        block: |
          [target.'cfg(target_os = "linux")']
          rustflags = ["-C", "link-arg=-fuse-ld=mold"]

    # Golang
    - name: Install Golang
      apt:
        name: golang
      become: yes

    - name: Add go workspace's bin directory to global PATH
      lineinfile:
        path: ~/.bashrc
        line: export PATH=$PATH:$(go env GOPATH)/bin
        create: yes
    #TODO: go bash auto completion

    # JavaScript
    - name: Check if Volta is installed
      stat:
        path: ~/.volta
      register: volta_installed

    - name: Install Volta
      shell: >
        curl https://get.volta.sh | bash
      when: not volta_installed.stat.exists
